/*
 * Copyright 2012 MicroStrain Inc. All Rights Reserved.
 *
 * Distributed under the Simplified BSD License.
 * See file license.txt
 *
 */

package com.sensorcloud;

/*
 * 
 * Base class for all Exceptions generated by the SensorCloud library
 * 
 * 
 * 
 */

@SuppressWarnings("serial")
public class SensorCloudException extends RuntimeException 
{	
	public SensorCloudException(String msg)
	{
		super(msg);
	}
	
	
	/*
	 * Wrap an exception as a SensorCloud exception
	 */
	public SensorCloudException(Exception e)
	{
		super(e);
	}
	
	
	/*
	 * Wrap an exception as a SensorCloud exception with a message
	 */
	public SensorCloudException(String msg, Exception e)
	{
		super(msg, e);
	}
	
	
	
	public static class AuthenticationError extends SensorCloudException
	{
		public AuthenticationError()
		{
			super("Failed to authenticate");
		}
		
		public AuthenticationError(String msg)
		{
			super(msg);
		}
		
	}
	

	

}
